version: "3"
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luna123456
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./logs:/var/log/mysql
      - ./mysql-files:/var/lib/mysql-files